import Foundation

/// Cursor: a `stop` hook in ~/.cursor/hooks.json, JSON on stdin. The
/// registered command is a wrapper script in ~/.cursor (a space-free path,
/// because the real helper sits under "Application Support" and we don't know
/// whether Cursor shell-parses the command).
struct CursorAgent: AgentModule {
    let name = "Cursor"
    let hookSubcommands = ["cursor"]
    let payloadSource = PayloadSource.stdin
    let installDetail = "Adds a stop hook to ~/.cursor/hooks.json. Like Codex, Cursor only reports when a task finishes (no attention events)"
    // Cursor's agent panel can be hidden while you code in the same window, so
    // being in Cursor does not mean you saw the run finish.
    let bypassesWatchingFilter = true
    let cliBinaryName = "cursor-agent"

    func wrapperContent() -> String {
        """
        #!/bin/bash
        # Generated by NotCode. Cursor invokes this on its stop hook; the JSON
        # payload on stdin flows through exec to the helper.
        exec \(HookInstaller.shellEscape(Paths.installedHelper.path)) cursor
        """
    }

    // MARK: - Hooks (~/.cursor/hooks.json)

    func hookStatus() -> HookInstaller.Status {
        guard let object = readHooks() else { return .notInstalled }
        let hooks = object["hooks"] as? [String: Any] ?? [:]
        let entries = hooks["stop"] as? [[String: Any]] ?? []
        return containsOurHook(entries) ? .installed : .notInstalled
    }

    func installHooks() throws {
        try FileManager.default.createDirectory(
            at: Paths.cursorWrapper.deletingLastPathComponent(), withIntermediateDirectories: true)
        try wrapperContent().write(to: Paths.cursorWrapper, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755], ofItemAtPath: Paths.cursorWrapper.path)

        let merged = merged(into: readHooks() ?? [:])
        try HookInstaller.backup(Paths.cursorHooks)
        try HookInstaller.writeJSON(merged, to: Paths.cursorHooks)
    }

    func uninstallHooks() throws {
        defer { try? FileManager.default.removeItem(at: Paths.cursorWrapper) }
        guard var object = readHooks(),
              var hooks = object["hooks"] as? [String: Any],
              var entries = hooks["stop"] as? [[String: Any]] else { return }
        entries.removeAll {
            ($0["command"] as? String)?.contains(HookInstaller.helperMarker) == true
        }
        if entries.isEmpty { hooks.removeValue(forKey: "stop") } else { hooks["stop"] = entries }
        object["hooks"] = hooks
        try HookInstaller.backup(Paths.cursorHooks)
        try HookInstaller.writeJSON(object, to: Paths.cursorHooks)
    }

    /// Pure merge: adds our stop hook to a hooks.json object, preserving
    /// everything already there. Idempotent.
    func merged(into object: [String: Any]) -> [String: Any] {
        var object = object
        if object["version"] == nil { object["version"] = 1 }
        var hooks = object["hooks"] as? [String: Any] ?? [:]
        var entries = hooks["stop"] as? [[String: Any]] ?? []
        if !containsOurHook(entries) {
            entries.append(["command": Paths.cursorWrapper.path])
        }
        hooks["stop"] = entries
        object["hooks"] = hooks
        return object
    }

    private func readHooks() -> [String: Any]? {
        guard let data = try? Data(contentsOf: Paths.cursorHooks) else { return nil }
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    private func containsOurHook(_ entries: [[String: Any]]) -> Bool {
        entries.contains {
            ($0["command"] as? String)?.contains(HookInstaller.helperMarker) == true
        }
    }

    // MARK: - Events

    /// Cursor's stop hook passes JSON on stdin, e.g.
    /// {"hook_event_name":"stop","status":"completed","conversation_id":"...",
    ///  "workspace_roots":["/path"],"loop_count":0}
    /// Returns nil for status "aborted": the user cancelled the turn, so
    /// they're at the machine and a ding would be noise.
    func parse(subcommand: String, payload: Data) -> AgentEvent? {
        let object = (try? JSONSerialization.jsonObject(with: payload)) as? [String: Any] ?? [:]
        if object["status"] as? String == "aborted" { return nil }
        return AgentEvent(
            agent: name,
            kind: .done,
            detail: nil,
            cwd: (object["workspace_roots"] as? [String])?.first,
            sessionID: object["conversation_id"] as? String)
    }

    // MARK: - Remote resume

    func resumeAvailability() -> ResumeAvailability {
        loginShellWhich("cursor-agent")
            ? .available
            : .unavailable(reason: "install Cursor's cursor-agent CLI to reply to Cursor sessions")
    }

    func resumeCommand(sessionID: String, prompt: String) -> String? {
        "cursor-agent -p --resume \(HookInstaller.shellEscape(sessionID)) "
            + "-- \(HookInstaller.shellEscape(prompt))"
    }
}
